# Generated by Django 5.0 on 2023-12-16 14:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField()),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='studygroup',
            new_name='study_group',
        ),
        migrations.RenameField(
            model_name='studygroup',
            old_name='current_member',
            new_name='max_members',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='max_member',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='role',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='study_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studygroup',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studygroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studygroup',
            name='study_end_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studygroup',
            name='study_start_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studygroup',
            name='thumnail',
            field=models.ImageField(blank=True, upload_to='study_images/'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studygroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='study.category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studygroup', to=settings.AUTH_USER_MODEL)),
                ('studygroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studygroup', to='study.studygroup')),
            ],
        ),
    ]
