# Generated by Django 5.0 on 2023-12-19 01:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="studymember",
            name="role",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="studymember",
            unique_together={("study_group", "user")},
        ),
    ]
