# Generated by Django 5.0 on 2023-12-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studygroup",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="study_images/"),
        ),
    ]
