# Generated by Django 5.0 on 2023-12-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0002_alter_studymember_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studygroup",
            name="level",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studygroup",
            name="week_days",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="study_end_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
