# Generated by Django 5.0 on 2023-12-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_category_rename_studygroup_comment_study_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroup',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
