# Generated by Django 5.0 on 2023-12-17 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0003_rename_thumnail_studygroup_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studygroup",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="study.category",
            ),
        ),
    ]
