# Generated by Django 5.0 on 2023-12-17 04:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatroom",
            old_name="study",
            new_name="study_group",
        ),
    ]
