# Generated by Django 5.0 on 2023-12-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyususer',
            options={},
        ),
        migrations.AlterModelManagers(
            name='studyususer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='studyususer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studyususer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studyususer',
            name='username',
        ),
        migrations.AlterField(
            model_name='studyususer',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studyususer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studyususer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
