# Generated by Django 5.0 on 2023-12-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_studyususer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyususer',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
